# Jekyll configuration
title: "LuizLeme Site - Posts e vídeos techs, em português, diretos e simples você só encontra aqui!"
url: 'http://luizhenriqueleme.github.io'
author: Luiz Leme
github: 'luizhenriqueleme'
email: 'developer.luizhenriqueleme@outlook'
description: 'Posts and tutorials about Java, Android, JavaScript, Hibernate, Spring, Web Development and others development stuffs SuelenGC'

category_title_prefix: ''
category_dir: /

# Basic configuration
permalink: /:year/:title/
destination: ./_publish
tag_dir: tag

# Use Pygments to highlight code blocks
baseurl: '/'
highlighter: pygments
paginate: 10
exclude: ['/node_modules', '/.gitignore', './config.ru', './Gemfile', './Gemfile.lock', './CNAME', '/gulpfile.js', '/package.json', '/README.md', '/src']

# Google Analytics configuration
analytics : 
  provider : google
  google : 
    tracking_id : ''

# Publish posts with future date.
future: false

# Compile posts in the _drafts directory.
show_drafts: false

gems: ['jekyll-paginate']
