title: "Luiz Henrique Leme Site- Posts e videos techs, em português, diretos e simples você só encontra aqui!"
url: 'http://luizhenriqueleme.github.io'
author: Luiz Leme
github: luizhenriqueleme
email: developer.luizhenriqueleme@outlook.com
description: 'Posts and tutorials about Java, Android, Hibernate, Spring, JavaScript, Angular,Web Development and others development stuffs LuizLeme'
 
category_title_prefix: ''
category_dir: /

# Basic configuration
permalink: /:year/:title/
destination: ./_publish
tag_dir: tag

# Use Pygments to highlight code blocks
baseurl: '/'
highlighter: pygments
paginate: 10
exclude: ['/node_modules', '/.gitignore', './config.ru', './Gemfile', './Gemfile.lock', './CNAME', '/gulpfile.js', '/package.json', '/README.md', '/src']

# Publish posts with future date.
future: false

# Compile posts in the _drafts directory.
show_drafts: false

gems: ['jekyll-paginate']
