# Site settings
title: Luiz H Leme - Desenvolvedor Web Full Stack
description: Um blog de um desenvolvedor Web Full Stack, Pesquisador e entusiasta de novas tecnologias.
baseurl: '/' # the subpath of your site, e.g. /blog
url: "https://www.luizhleme.com.br" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Luiz H Leme
user_description: Pesquisador, Entusiasta Ágil, Desenvolvedor Web Full Satck, Desenvolvedor Mobile
email: developer.luizhenriqueleme@outlook.com
twitter_username: dev_luizleme
github_username:  luizhenriqueleme
gplus_username:  luizleme.86@gmail.com
disqus_username: luizhenriqueleme

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Séries
    url: /series
  - title: Tags
    url: /tags
  - title: Sobre min
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
